name: Deploy to FTP Server

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          composer install
      - name: Update dependencies
        run: composer update
      

      - name: 📂 Sync files to Ftp server
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{secrets.SERVER}}
          username: magento2divya
          password: ${{secrets.PASSWORD}}
          server-dir: ${{secrets.PATH}}/
          exclude: |
            **/vendor/**
            **/var/**
            **/generated/**
            **/pub/**
            **/setup/**
            **/phpserver/**
            **/dev/**
            **/bin/**
            **/stats/**
            **/lib/**
      - name: Executing Upgrade,Compile,Deploy commands 
        uses: appleboy/ssh-action@v0.1.7
        with:
         host: ${{secrets.SERVER}}
         username: magento2divya
         password: ${{secrets.PASSWORD}}
         port: 22
         script: ls && cd ${{secrets.PATH}} && pwd && php bin/magento setup:upgrade && php bin/magento setup:di:compile && php bin/magento setup:static-content:deploy -f && php bin/magento c:f
         timeout: 60000s