name: Deploy to FTP Server

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: 📂 Sync files to Ftp server
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{secrets.SERVER}}
          username: magento2divya
          password: ${{secrets.PASSWORD}}
          server-dir: /home/magento2divya/public_html/
          exclude: |
            **/vendor/**
            **/var/**
            **/generated/**
            **/pub/**
            **/setup/**
            **/phpserver/**
            **/dev/**
            **/bin/**
            **/stats/**
            **/lib/**
      - name: Executing Upgrade,Compile,Deploy commands 
        uses: appleboy/ssh-action@v0.1.7
        with:
         host: ${{secrets.SERVER}}
         username: magento2divya
         password: ${{secrets.PASSWORD}}
         port: 22
         debug: true
         script: ls && cd /home/magento2divya/public_html && pwd && ls -lart && php81 bin/magento setup:upgrade && php81 bin/magento setup:di:compile && php81 bin/magento setup:static-content:deploy -f && php81 bin/magento c:f
         command_timeout: 20m
